import type { EncounterKind } from '@aop/engine'

const BASE = '/audio/generated'

/**
 * The 10 NPC/narrator dialogue clips generated by the local Piper TTS pipeline
 * (#75, PR #78). Filenames are the stable contract with
 * `apps/web/public/audio/generated/`.
 */
export const DIALOGUE = {
  merchantGreet: `${BASE}/merchant_greet.wav`,
  merchantFarewell: `${BASE}/merchant_farewell.wav`,
  nativeWarning: `${BASE}/native_warning.wav`,
  nativeTrade: `${BASE}/native_trade.wav`,
  settlerPlea: `${BASE}/settler_plea.wav`,
  settlerGratitude: `${BASE}/settler_gratitude.wav`,
  battleCharge: `${BASE}/battle_charge.wav`,
  battleTaunt: `${BASE}/battle_taunt.wav`,
  narratorIntro: `${BASE}/narrator_intro.wav`,
  levelComplete: `${BASE}/level_complete.wav`,
} as const

/** Greeting bark played once when an encounter sheet opens, keyed by kind. */
export const ENCOUNTER_GREETING: Record<EncounterKind, string> = {
  merchant: DIALOGUE.merchantGreet,
  natives: DIALOGUE.nativeWarning,
  settlers: DIALOGUE.settlerPlea,
}
