// GENERATED by scripts/generate-engine-version.mjs — do not hand-edit.
// Regenerate after any packages/engine/src or packages/content/src change:
//   node scripts/generate-engine-version.mjs
export const ENGINE_VERSION = '6e8fe41bda8259c5'
